services:
  mqtt:
    build: ./mosquitto
    ports:
      - "1883:1883"
    networks:
      aquasenseNet:
        ipv4_address: 172.25.0.2

  frontend:
    build: ./frontend
    ports:
      - "80:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - mqtt
    networks:
      aquasenseNet:
        ipv4_address: 172.25.0.3

networks:
  aquasenseNet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16