services:
  mqtt:
    build: ./backend/mosquitto
    ports:
      - "1883:1883"
    networks:
      aquasenseNet:
        ipv4_address: 172.25.0.2
  mysql:
    build: ./backend/mysql
    ports:
      - "3306:3306"
    networks:
      aquasenseNet:
        ipv4_address: 172.25.0.3

  frontend:
    build: ./frontend
    ports:
      - "80:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_IP: mysql
    depends_on:
      - mqtt
      - mysql
    networks:
      aquasenseNet:
        ipv4_address: 172.25.0.4

networks:
  aquasenseNet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

        
